
default:
	(cd ./snapshot_pod ; make ; cd ../snapshot_pod_mpi ; make ; cd ../pod_reconstruction ; make ; cd ../pod_reconstruction_mpi ; make)

clean:
	(cd ./snapshot_pod ; make clean ; cd ../snapshot_pod_mpi ; make clean ; cd ../pod_reconstruction ; make clean ; cd ../pod_reconstruction_mpi ; make clean)
