# Libraries made in order so that interdepancies are taken into account
#
default:
	(cd ./libUtils ; make ; cd ../libPodUtils ; make)

clean:
	(cd ./libUtils ; make clean ; cd ../libPodUtils ; make clean)

